runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /src
  static_dir: src
  secure: always

- url: /stylesheets
  static_dir: stylesheets
  secure: always

- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always

- url: /get-started.html
  static_files: get-started.html
  upload: get-started.html
  secure: always

- url: /extend.html
  static_files: extend.html
  upload: extend.html
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
